package com.m3958.firstgwt.client.types;

public enum ViewNameEnum {
	MMENU,TOP,NOVIEW,USER,USER_EDIT,GROUP,GROUP_EDIT,ROLE,ROLE_EDIT,DEPARTMENT,DEPARTMENT_EDIT,FIELD_ENUM,FIELD_ENUM_EIDT,
	HELP_MESSAGE,OBJECT_CLASS,OBJECT_CLASS_EDIT,SITE_CONFIG,SITECONFIG_EDIT,FEED_BACK,FEEDBACK_EDIT,
	FTL,FTL_EDIT,JRXML,JRXML_EDIT,TOOLS,MENULEVEL,MENUITEM,MENUITEM_EDIT,ASSET,LGB,LGB_EDIT,WEBSITE,WEBSITE_EDIT,WELCOME,STRIP,LEFT_STRIP,RIGHT_STRIP,
	MENULEVEL_EDIT,SHEQU,SHEQU_EDIT,ADDRESS_EDIT,CAREER_EDIT,STEP_CAREER_EDIT,FAMILY_EDIT,HOUSE_EDIT,REWARD_EDIT,ASSET_EDIT,
	ASSET_FOLDER,ASSET_FOLDER_EDIT,DISKFILE,DISKFILE_EDIT,WEBHOST,WEBHOST_EDIT,UPLOAD,SECTION,SECTION_EDIT,ARTICLE,ARTICLE_EDIT,
	LINK,LINK_EDIT,LOGIN,REGISTE,HGLL,HGLL_EDIT,XJ_CAT,XJ_CAT_EDIT,XINJIAN,XINJIAN_EDIT,HTMLCSS,HTMLCSS_EDIT,VOTE,VOTE_EDIT,VOTEHIT,
	COMMENT,COMMENT_EDIT,PAGE_MISTAKE,PAGE_MISTAKE_EDIT,HMESSAGE_RECEIVE
}
