// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.mycompany.roo.client.managed.activity;

import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.gwt.view.client.Range;
import com.google.web.bindery.requestfactory.shared.Receiver;
import com.google.web.bindery.requestfactory.shared.Request;
import com.mycompany.roo.client.managed.request.ApplicationRequestFactory;
import com.mycompany.roo.client.proxy.StudentProxy;
import com.mycompany.roo.client.scaffold.ScaffoldMobileApp;
import com.mycompany.roo.client.scaffold.activity.IsScaffoldMobileActivity;
import com.mycompany.roo.client.scaffold.place.AbstractProxyListActivity;
import com.mycompany.roo.client.scaffold.place.ProxyListView;
import java.util.List;

public abstract class StudentListActivity_Roo_Gwt extends AbstractProxyListActivity<StudentProxy> implements IsScaffoldMobileActivity {

    protected ApplicationRequestFactory requests;

    public StudentListActivity_Roo_Gwt(PlaceController placeController, ProxyListView<com.mycompany.roo.client.proxy.StudentProxy> view, Class<com.mycompany.roo.client.proxy.StudentProxy> proxyType) {
        super(placeController, view, proxyType);
    }

    protected void fireCountRequest(Receiver<java.lang.Long> callback) {
        requests.studentRequest().countAllStudents().fire(callback);
    }
}
