// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.mycompany.roo.client.managed.request;

import com.mycompany.roo.client.request.StudentRequest;
import com.mycompany.roo.shared.scaffold.ScaffoldRequestFactory;

public interface ApplicationRequestFactory extends ScaffoldRequestFactory {

    StudentRequest studentRequest();
}
