package com.smartgwt.sample.showcase.client;
// This file is automatically generated. Do not modify it manually.
import java.util.TreeMap;
class DataURLRecords {
private static TreeMap<String, String[]> _dataURLsMap;
private static final DataURLRecord[] _dataURLRecords = new DataURLRecord[] {

new DataURLRecord("AdvancedCubeSample","productRevenue.ds.xml"),
new DataURLRecord("BasicConnectorHibernateSample","worldHB.ds.xml"),
new DataURLRecord("BasicConnectorSample","worldDS.ds.xml"),
new DataURLRecord("BatchUploaderSample","supplyItemCustomHB.ds.xml"),
new DataURLRecord("BlockingValidationSample","complaint.ds.xml","masterDetail_orderHB.ds.xml"),
new DataURLRecord("Copy","employees.ds.xml","teamMembers.ds.xml"),
new DataURLRecord("CustomExportSample","worldDSExportCustom.ds.xml"),
new DataURLRecord("DMIValidationSample","StockItem.ds.xml","validationDMI_orderForm.ds.xml"),
new DataURLRecord("DmiCrudSample","supplyItemDMI.ds.xml"),
new DataURLRecord("DynamicReportingSample","dynamicReporting_orderItem.ds.xml"),
new DataURLRecord("ExcelExportSample","worldDSExport.ds.xml"),
new DataURLRecord("FlattenedDataModelSample","flattenedBeans_flatUserHB.ds.xml"),
new DataURLRecord("FormValidationSample","supplyItem.ds.xml"),
new DataURLRecord("FormattedExportSample","worldDSExport.ds.xml"),
new DataURLRecord("GridMassUpdateSample","countryDS.ds.xml"),
new DataURLRecord("HibernateProductionCrudSample","supplyItemSpringDMI.ds.xml"),
new DataURLRecord("JavaBeansGridSample","supplyItemDMI.ds.xml"),
new DataURLRecord("LargeValueMapSQLSample","largeValueMap_orderItem.ds.xml"),
new DataURLRecord("LiveGridFetchSample","supplyItem.ds.xml"),
new DataURLRecord("MasterDetailHibernateSample","masterDetail_orderHB.ds.xml","masterDetail_orderItemHB.ds.xml"),
new DataURLRecord("MultiRowDragSaveSample","employees.ds.xml","teamMembers.ds.xml"),
new DataURLRecord("ORMDataSourceSample","ormDataSource_country.ds.xml"),
new DataURLRecord("OfflineDataSourceSupportSample","supplyCategory.ds.xml","supplyItem.ds.xml"),
new DataURLRecord("QueuedMasterDetailAddSample","queuedAdd_order.ds.xml","queuedAdd_orderItem.ds.xml","supplyCategory.ds.xml","supplyItem.ds.xml"),
new DataURLRecord("RecategorizeList","supplyItem.ds.xml"),
new DataURLRecord("RecategorizeTile","animals.ds.xml"),
new DataURLRecord("RecategorizeTree","supplyCategory.ds.xml","supplyItem.ds.xml"),
new DataURLRecord("RelatedValidationSample","complaint.ds.xml","masterDetail_orderHB.ds.xml"),
new DataURLRecord("ReusableORMDataSourceSample","reusableORMDataSource_country.ds.xml","reusableORMDataSource_supplyItem.ds.xml"),
new DataURLRecord("ServerAdvancedFilteringHibernateSample","supplyItemHB.ds.xml"),
new DataURLRecord("ServerAdvancedFilteringSQLSample","worldDS.ds.xml"),
new DataURLRecord("SimpleCustomDataSourceSample","customDataSource_user.ds.xml"),
new DataURLRecord("SimpleQueuingSample","queuing_order.ds.xml","queuing_userHB.ds.xml"),
new DataURLRecord("TreeBindingSQLSample","employees.ds.xml"),
new DataURLRecord("TreeReparent","employees.ds.xml"),
new DataURLRecord("TreeReparentSample","employees.ds.xml"),
new DataURLRecord("UniqueValidationSample","queuing_userHB.ds.xml"),
new DataURLRecord("UploadSample","mediaLibrary.ds.xml"),
new DataURLRecord("UserSpecificDataSample","cartItem.ds.xml","supplyItem.ds.xml"),
new DataURLRecord("VelocityValidationSample","StockItem.ds.xml","velocity_orderForm.ds.xml")};
private static class DataURLRecord {
private String _className;
private String[] _urls;
private DataURLRecord(String className, String... urls) {
  _className = className;
  _urls = urls;
} // DataURLRecord()
} // class DataURLRecord
static String[] getDataURLs(final String className) {
  if (_dataURLsMap == null) {
    _dataURLsMap = new TreeMap<String, String[]>();
    for (DataURLRecord dataURLRecord : _dataURLRecords) {
      _dataURLsMap.put(dataURLRecord._className, dataURLRecord._urls);
    }
  }
  return _dataURLsMap.get(className);
} // getDataURLs()
}
