// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.mycompany.roo.client.managed.ui;

import com.google.gwt.text.shared.AbstractRenderer;
import com.mycompany.roo.client.managed.request.ApplicationEntityTypesProcessor;
import com.mycompany.roo.client.proxy.StudentProxy;
import com.mycompany.roo.client.scaffold.place.ProxyListPlace;

public abstract class ApplicationListPlaceRenderer_Roo_Gwt extends AbstractRenderer<ProxyListPlace> {

    public String render(ProxyListPlace object) {
        return new ApplicationEntityTypesProcessor<String>() {

            @Override
            public void handleStudent(StudentProxy isNull) {
                setResult("Students");
            }
        }.process(object.getProxyClass());
    }
}
