package com.m3958.firstgwt.client.types;


public enum SmartSubOperationName{
	FETCH_ONE_TO_MANY,MANY_TO_MANY,FETCH_CHILDREN,FETCH_TWO_JOIN,HAS_PERMISSION,NOT_CREATOR_HAS_PERMISSION,NOT_CREATOR_HAS_GPERMISSION,
	ADD_WITH_PARENT,UPDATE_WITH_PARENT,MANAGE_RELATION,CUSTOM_FETCH,ADMIN,FETCH_RELATION_COUNT,
	NO_SUB_OPERATION,EXPORT_LGB_TO_EXCEL,EXPORT_LGB_TO_PDF,FETCH_NO_RELATION,FETCH_ONE,UNIUQE_CHECK,
	AFTER_ADD_TREEMODEL,NAMED_QUERY,CREATE_OBJECT_PERMISSIONS,FETCH_SHARED_USERS,FETCH_SHARED_GROUPS,
	SHARE_TO_USER,SHARE_TO_GROUP,ADD_USER_TO_GROUP,MQ,UNZIP,ASSET_TO_DISK,
	REFRESH_SITE_CACHE,AUDIT_ONE,REMOTE_ASSET,REBUILD_SOLR_INDEX,PASTER_DISK_FILE;
}
