// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.roo.domain;

import com.mycompany.roo.domain.Student;

privileged aspect Student_Roo_JavaBean {
    
    public String Student.getName() {
        return this.name;
    }
    
    public void Student.setName(String name) {
        this.name = name;
    }
    
}
