
package com.skynet.spms.webservice.entity;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1
 * Fri May 27 14:45:04 CST 2011
 * Generated source version: 2.3.1
 * 
 */

@WebFault(name = "FaultOutputParameters", targetNamespace = "http://www.skynetsoft.org/RFIDwsdl")
public class FaultResponse extends Exception {
    public static final long serialVersionUID = 20110527144504L;
    
    private java.lang.String faultOutputParameters;

    public FaultResponse() {
        super();
    }
    
    public FaultResponse(String message) {
        super(message);
    }
    
    public FaultResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public FaultResponse(String message, java.lang.String faultOutputParameters) {
        super(message);
        this.faultOutputParameters = faultOutputParameters;
    }

    public FaultResponse(String message, java.lang.String faultOutputParameters, Throwable cause) {
        super(message, cause);
        this.faultOutputParameters = faultOutputParameters;
    }

    public java.lang.String getFaultInfo() {
        return this.faultOutputParameters;
    }
}
